# This section controls the navigation and nesting of pages, including their titles
pages:
- Home: 'index.md'
- Products:
  - Introduction: 'products/index.md'
  - Ask: 'products/ask.md'
  - Talk: 'products/talk.md'
  - Trust: 'products/trust.md'
- Get Involved:
  - Introduction: 'contribute/index.md'
  - Contribute code: 'contribute/writing_code.md'
  - Contribute to moderation style guide: 'contribute/docs_style_guide.md'
  - Write documentation: 'contribute/writing_documentation.md'
  - Code best practices: 'contribute/coding_style_guide.md'
  - Submit feature requests: 'contribute/reporting_bugs.md'
  - Report bugs: 'contribute/reporting_bugs.md'
  - Our Code of Conduct: 'contribute/code_of_conduct.md'
- Contact: 'contact/support.md'
- FAQ: 'contact/faq.md'



# Site specific MkDocs configuration for Coral Project

site_name: Coral Project

repo_url: https://github.com/coralproject/ask

repo_name: 'GitHub'

docs_dir: 'docs_dir'

theme_dir: 'themes'

theme: 'material' 

markdown_extensions:
  - admonition
  - fenced_code
  - sane_lists
  - smarty
  - codehilite(css_class=code)

google_analytics: ['UA-73335347-3', 'docs.coralproject.net']

# Theme Options - MkDocs Material 

extra:
  logo: 'images/coralproject_logo250.png'
  palette:
    primary: 'blue grey'
    accent: 'cyan'
  author:
    github: 'coralproject'  
