# If you add a page, you must add it to the index here
pages:
- Home: 'index.md'
- Products:
  - User Guide: 'products/index.md'
  - Ask: 'products/ask.md'
  - Talk: 'products/talk.md'
  - Trust: 'products/trust.md'
- Developers:
  - Introduction: 'developer/index.md'
  - Architectural overview: 'developer/architectural_overview.md'
  - Installing Coral Ecosystem: 'developer/quickstart/install.md'
  - Developer tools setup: 'developer/developer_setup.md'
  - Cay: 'developer/cay/index.md'
  - Elkhorn: 'developer/elkhorn/index.md'
  - Pillar: 'developer/pillar/index.md'
  - Sponge: 'developer/sponge/index.md'
  - Xenia: 'developer/xenia/index.md'
  - Xenia Driver: 'developer/xenia/xenia-driver-js.md'
- Get Involved:
  - Introduction: 'contribute/index.md'
  - Contribute code: 'contribute/writing_code.md'
  - Contribute to moderation style guide: 'contribute/docs_style_guide.md'
  - Write documentation: 'contribute/writing_documentation.md'
  - Code best practices: 'contribute/coding_style_guide.md'
  - Submit feature requests: 'contribute/reporting_bugs.md'
  - Report bugs: 'contribute/reporting_bugs.md'
  - Our Code of Conduct: 'contribute/code_of_conduct.md'
- Contact:
  - Technical Support: 'contact/support.md'
  - FAQ: 'contact/faq.md'



# Site specific MkDocs configuration for Coral Project

site_name: Coral Project Docs

repo_url: https://github.com/coralproject/docs/

repo_name: 'GitHub'

docs_dir: 'docs_dir'

theme_dir: 'cinder'

theme: 'cinder' 


markdown_extensions:
  - admonition
  - fenced_code
  - sane_lists
  - smarty

google_analytics: ['UA-73335347-3', 'docs.coralproject.net']



