# If you add a page, you must add it to the index here
pages:
- Home:
  - About: 'index.md'
  - Architectural overview: 'coral_ecosystem.md'
- Developer Guide:
  - Installing Coral Ecosystem: 'quickstart/install.md'
  - Setting up MongoDB: 'quickstart/mongodb.md'
  - Cay:
    - Introduction: 'cay/index.md'
    - Installation: 'cay/install.md'
  - Elkhorn:
    - Introduction: 'elkhorn/index.md'
    - Installation: 'elkhorn/install.md'
  - Pillar:
    - Introduction: 'pillar/index.md'
    - Installation: 'pillar/install.md'
    - API: 'pillar/api.md'
  - Sponge:
    - Introduction: 'sponge/index.md'
    - Installation: 'sponge/install.md'
    - Included packages: 'sponge/included_packages.md'
    - Roadmap: 'sponge/roadmap.md'
    - Logging: 'sponge/logging.md'
  - Xenia:
    - Introduction: 'xenia/index.md'
    - Installation: 'xenia/install.md'
    - API and query management: 'xenia/api.md'
    - Testing: 'xenia/tests.md'
  - Xenia Driver:
    - Introduction: 'xenia/xenia-driver-js.md'
    - Installation: 'xenia/xenia-driver-js-install.md'
    - API: 'xenia/xenia-driver-js-api.md'
- User Guide:
  - Introduction: 'contributions/index.md'
- Contribute:
  - Introduction: 'contributions/index.md'
  - Writing documentation: 'contributions/documentation/writing_documentation.md'
  - Reporting bugs and requesting features: 'contributions/reporting_bugs.md'
  - Supporting the community: 'contributions/supporting_the_community.md'
  - Contributor License Agreement: 'contributions/contributor_license_agreement.md'
  - DEVELOPMENT:
    - Writing code: 'contributions/development/writing_code.md'
    - Development workflow: 'contributions/development/working_with_github.md'
    - Coding style: 'contributions/development/code_style.md'
- FAQ: 'faq.md'


# Do not edit in PRs below here
site_name: Coral Project Docs

markdown_extensions:
  - admonition
  - fenced_code
  - sane_lists
  - smarty

theme: mkdocs

docs_dir: './'
