version: '2'
services:
  mongodata:
    image: coralproject/mongodata
    restart: always
    environment:
      - "MONGO_DUMP=https://s3.amazonaws.com/coral-demo-dataset/dump.tar.gz"
      - "MONGO_USER=${MONGO_USER}"
      - "MONGO_PASS=${MONGO_PASS}"
      - "MONGO_DB=${MONGO_DB}"
    volumes:
      - /mongodata:/data/db
    ports:
      - "27017"

  rabbitmq:
    image: rabbitmq:management
    restart: always
    environment:
      - "RABBITMQ_DEFAULT_USER=${RABBIT_USER}"
      - "RABBITMQ_DEFAULT_PASS=${RABBIT_PASS}"
    ports:
      - "15672:15672"
      - "5672:5672"

  pillarapp:
    image: coralproject/pillar
    restart: always
    depends_on:
      - rabbitmq
    environment:
        - "PILLAR_HOME=/opt/pillar"
        - "PILLAR_ADDRESS=:8080"
        - "MONGODB_URL=mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017/${MONGO_AUTHDB}"
        - "AMQP_EXCHANGE=PillarMQ"
        - "PILLAR_CRON=false"
        - "PILLAR_CRON_SEARCH=@every 30m"
        - "XENIA_URL=http://xeniaapp:4000/1.0/exec/"
        - "XENIA_QUERY_PARAM=?skip=0&limit=100"
        - "XENIA_AUTH=<auth token>"
        - "AMQP_URL=amqp://${RABBIT_USER}:${RABBIT_PASS}@rabbitmq:5672/"
    ports:
     - "8080"
    links:
      - mongodata
      - rabbitmq

  atollapp:
    image: coralproject/atoll
    restart: always
    ports:
      - "8181"
    links:
      - mongodata

  xeniaapp:
    image: coralproject/xenia
    restart: always
    environment:
      - "XENIA_MONGO_HOST=mongodata:27017"
      - "XENIA_MONGO_AUTHDB=admin"
      - "XENIA_MONGO_DB=${MONGO_DB}"
      - "XENIA_MONGO_USER=${MONGO_USER}"
      - "XENIA_MONGO_PASS=${MONGO_PASS}"
      - "XENIA_LOGGING_LEVEL=1"
      - "XENIA_HOST=:4000"
      - "XENIA_CREATE_DATABASE=${XENIA_CREATE_DATABASE}"
      - "XENIA_UPDATE_QUERY=${XENIA_UPDATE_QUERY}"
      - "XENIA_DATABASE_SCHEMA_PATH=${XENIA_DATABASE_SCHEMA_PATH}"
      - "XENIA_QUERY_UPSERT_PATH=${XENIA_QUERY_UPSERT_PATH}"
    ports:
      - "4000"
    links:
      - mongodata

  cayapp:
    image: coralproject/cay
    restart: always
    environment:
       - "XENIA_URL=https://${FRONTEND_HOST}/xenia_demo/"
       - "PILLAR_URL=https://${FRONTEND_HOST}/pillar_demo/"
       - "ENV=staging"
       - "PROJECT=Coral Project"
       - "GAID=${GAID_VALUE}"
       - "AUTH_TOKEN=${AUTH_TOKEN_VALUE}"
    ports:
      - "80:80"
    links:
      - pillarapp
      - xeniaapp
      - mongodata

  elkhorn:
    image: coralproject/elkhorn
    restart: always
    ports:
      - "4444:4444"
    volumes:
      - ./elkhorn/config.json:/usr/src/app/config.json
    links:
      - pillarapp:pillar

  sponge:
    image: coralproject/sponge
    restart: always
    mem_limit: 1g
    environment:
      - "STRATEGY_CONF=/usr/local/strategy.json"
      - "PILLAR_URL=${FRONTEND_HOST}:8080"
    volumes:
      - ./sponge/assets/strategy.json:/usr/local/strategy.json

  proxy:
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./proxy/:/etc/nginx/conf.d/
      - ./certs/:/etc/ssl/certs/
    links:
      - atollapp:atoll
      - pillarapp:pillar
      - xeniaapp:xenia
      - cayapp:cay
    ports:
      - "8080:80"
      - "443:443"
